OPENAI_API_KEY = "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"
API_URL = "https://api.openai.com"
